
```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(measurements)
library(sqldf)
library(ggplot2)
library(RColorBrewer)
library(plotly)
library(reshape2)
library(kableExtra)
library(wordcloud)
library(wordcloud2)
```

```{r processing}
## Create additional functions

# Mode average
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

convertHeight <- function(x) {
    x <- as.character(x)
    split <- strsplit(x, "-")
    feet <- as.numeric(split[[1]][1])
    inch <- as.numeric(split[[1]][2])
    round(conv_unit(feet, "ft", "cm") + conv_unit(inch, "inch", "cm"),0)
}

# Load the data.

NBA <- read.csv("NBA/Seasons_Stats.csv")[, c(2:9, 11:20, 32:53)]
PlayerData <- read.csv("NBA/player_data.csv")[, c(1:3, 5:6)]

# Remove NA rows
NBA <- NBA %>% filter(!is.na(Year), !is.na(Player))

# Remove Team = TOT (which indicates total, when player played in more than 1 team in a season)
NBA <- NBA[NBA$Tm != "TOT",]

# Remove of "*" which indicates a player is a member of NBA Hall of Fame
NBA$Player <- gsub("\\*$", "", NBA$Player)

# Fix player data
PlayerData[2143, 4] = as.factor("6-2")
PlayerData[2143, 5] = 190
NBA[21304, 3] = "SG"

#Renaming some columns of the dataset

colnames(PlayerData) <- c("Name", "YearStart", "YearEnd", "Height-feet", "Weight-lbs")

# Merging data

NBA <- sqldf("SELECT * FROM NBA JOIN PlayerData ON NBA.Player = PlayerData.Name 
      WHERE NBA.Year >= PlayerData.YearStart AND NBA.Year <= PlayerData.YearEnd")

# Fixing Position

# In here, for simplicity and aesthetical purpose, I arbitrarily framed up all the players into the standard five position used today and then color-coded them:

NBA$Pos[NBA$Pos == "C-F"] <- "C"
NBA$Pos[NBA$Pos == "F-C"] <- "PF"
NBA$Pos[NBA$Pos == "F"] <- "PF"
NBA$Pos[NBA$Pos == "F-G"] <- "SF"
NBA$Pos[NBA$Pos == "G"] <- "SG"
NBA$Pos[NBA$Pos == "G-F"] <- "SF"
NBA$Pos <- factor(NBA$Pos, levels = c("C", "PF", "SF", "SG", "PG"))
PosColorCode <- c("C"="#FF0000", "PF"="#FFA500", "SF"="#DDDD00" ,"SG"="#0000FF", "PG"="#32CD32")

# Create new variables:

NBA <- NBA %>%
    rowwise() %>%
    mutate(Height = convertHeight(`Height-feet`),
           Weight = round(conv_unit(`Weight-lbs`, "lbs", "kg"),0),
           BMI = round(Weight / (Height / 100)^2, 2),
           Born = Year - Age,
           ORpG = ORB / G,
           DRpG = DRB / G,
           RpG = TRB / G,
           ApG = AST / G,
           SpG = STL / G,
           BpG = BLK / G,
           TpG = TOV / G,
           PpG = PTS / G,
           Position = cell_spec(Pos,
                            color = "white",
                            align = "c",
                            background = factor(Pos, c("C", "PF", "SF", "SG", "PG"),
                                                PosColorCode)))

# Arrange the table.

NBA <- NBA %>%
    select(Year:MP, YearStart:BMI, "Born", FG:PTS, TS.:TOV., ORpG:PpG, "Position", -c("Height-feet", "Weight-lbs"))

# Create duplicate table with normalized stats.

NBA_Scaled <- NBA
NBA_Scaled[, c(6:8, 15:54)] <- scale(NBA[, c(6:8, 15:54)])
```

```{r Teamscores, fig.width=9, fig.height=5, warning=FALSE}
Team_Scores <- NBA %>%
    group_by(Year) %>%
    summarise(Total_PTS = sum(PTS),
            Total_2FG = sum(X2P)*2,
            Total_3FG = sum(X3P, na.rm = T)*3,
            Total_FT = sum(FT),
            nTeam = n_distinct(Tm),
            nGames = max(G),
            Total_G = round((nGames*nTeam)/2, 0),
            FG2 = round((Total_2FG/Total_G)/2, 2),
            FG3 = round((Total_3FG/Total_G)/2, 2),
            FT = round((Total_FT/Total_G)/2, 2),
            avg_Tm_Scores = round((Total_PTS/Total_G)/2, 2)) %>%
    gather(Parameter, Count, FG2:FT, -c(Year:Total_G, avg_Tm_Scores))

Team_Scores %>%
    group_by(Year, Parameter) %>%
    ggplot(aes(Year, Count, fill=forcats::fct_rev(Parameter))) + 
    geom_bar(stat="identity") +
    geom_hline(yintercept = mean(Team_Scores$avg_Tm_Scores), col = "blue", alpha = 0.5) +
    ggtitle("Annual Team Scores per Game") +
    guides(fill=guide_legend(title="")) +
    xlab("Year") +
    ylab("Score per Game") +
    scale_fill_manual(name="", values=c("#FF5555", "#008500", "#0055FF")) +
    scale_x_continuous(breaks = seq(1950, 2020, 10)) +
    theme(legend.position="bottom")
```

```{r ppgpos, message=FALSE, warning=FALSE}
MeanPPG <- NBA %>%
    group_by(Year) %>%
    summarise(Average = round(sum(PTS)/sum(G), 2))

AvgPosPPGbyYear <- NBA %>%
    group_by(Year, Pos) %>%
    summarise(PPG = round(sum(PTS)/sum(G), 1)) %>%
    dcast(Year ~ Pos) %>%
    bind_cols(MeanPPG[,2])

AvgPosPPGbyYear %>%
    kable(escape = FALSE, align='c', caption = "Points per Game by Position") %>%
    kable_styling("striped", full_width = T) %>%
    column_spec(1, bold = T) %>%
    scroll_box(width = "100%", height = "300px")
```

```{r PPGPos, fig.width = 9, fig.height=5}
PosPPG <- AvgPosPPGbyYear %>%
    plot_ly(x = ~Year, opacity=0.5) %>%
    add_lines(y = ~C, name = "C", mode = 'lines', line=list(color='#FF0000')) %>%
    add_lines(y = ~PF, name = "PF", mode = 'lines', line=list(color='#FFA500')) %>%
    add_lines(y = ~SF, name = "SF", mode = 'lines', line=list(color='#DDDD00')) %>%
    add_lines(y = ~SG, name = "SG", mode = 'lines', line=list(color='#0000FF')) %>%
    add_lines(y = ~PG, name = "PG", mode = 'lines', line=list(color='#32CD32')) %>%
    add_lines(y = ~Average, name = "Average", mode = 'marker', opacity=1) %>%
    layout(legend = list(orientation = 'h'),
           title = 'Annual Points per Game by Position',
           yaxis = list(title = "Points per Game"),
           xaxis = list(title = ""))

#PosPPGChart <- api_create(PosPPG, filename = "PosPPG")
#PosPPGChart
```

```{r DecadePts, fig.width = 9, fig.height=5, warning=FALSE}
NBA %>%
    mutate(Decade = as.factor(ifelse(Year %in% 1950:1959, "1950-59",
                               ifelse(Year %in% 1960:1969, "1960-69",
                                      ifelse(Year %in% 1970:1979, "1970-79",
                                             ifelse(Year %in% 1980:1989, "1980-89",
                                                    ifelse(Year %in% 1990:1999, "1990-99",
                                                           ifelse(Year %in% 2000:2010, "2000-09",
                                                                  "2010+")))))))) %>%
    group_by(Pos, Decade) %>%
    summarise(PTS = sum(PTS)) %>%
    ggplot(aes(Pos, PTS, fill=forcats::fct_rev(Decade))) + 
    geom_bar(stat="identity") +
    ggtitle("Points Distribution by Position") +
    guides(fill=guide_legend(title="Decades")) +
    xlab("Position") +
    ylab("Points") +
    scale_fill_brewer(palette="Set2")
```

```{r alltimeppg, fig.width = 9, fig.cap="All", warning=FALSE}
AllTimePPG <- NBA %>%
    group_by(Player) %>%
    summarise(Pos = getmode(Pos),
              Team = getmode(Tm),
              ActiveYears = paste(getmode(YearStart), "-", getmode(YearEnd)),
              Games = sum(G),
              Points = sum(PTS),
              PPG = round(Points/Games, 2)) %>%
    filter(Games >= 400 | Points > 10000) %>%
    arrange(desc(PPG)) %>%
    head(n=20) %>%
    mutate(Rank = dense_rank(desc(PPG))) %>%
    select(Rank, everything())

AllTimePPG %>%
    mutate(Pos = cell_spec(Pos, color = "white", align = "c", 
                    background = factor(Pos, c("C", "PF", "SF", "SG", "PG"), 
                                        PosColorCode))) %>%
    kable(escape = FALSE, caption = "All-Time Points per Game Leaders") %>%
    kable_styling("striped", full_width = T) %>%
    column_spec(2, bold = T) %>%
    column_spec(1, bold = T, color = "yellow", background = "#FF0000") %>%
    column_spec(8, bold = T, color = "white", background = "#777777") %>%
    scroll_box(width = "100%", height = "300px")
```

```{r AllTimePPG, fig.width = 9, fig.height=5, warning=FALSE}
PPGAll <- NBA %>%
    filter(Player %in% head(AllTimePPG$Player, 10)) %>%
    group_by(Age, Player) %>%
    summarise(Games = sum(G),
              Points = sum(PTS),
              PPG = round(Points/Games, 2)) %>%
    ggplot() +
    geom_line(aes(Age, PPG, color=Player), alpha = 1) +
    ggtitle("All-Time Top Scorers' Chronological PPG") +
    theme(legend.position="bottom")

#ggplotly(PPGAll, session="knitr", kwargs=list(filename="PPGall_knitr", fileopt="overwrite"))
```

```{r AllTimePPGPos}
TopPPGPos <- AllTimePPG %>%
    group_by(Pos) %>%
    summarise(Player = Player[which.max(PPG)],
              Team = Team[which.max(PPG)],
              ActiveYears = ActiveYears[which.max(PPG)],
              Games = Games[which.max(PPG)],
              PPG = PPG[which.max(PPG)])
```

```{r topscorers, warning=FALSE}
TopScorer <- NBA %>%
    group_by(Year) %>%
    summarise(Player = as.character(Player[which.max(PpG)]),
              Team = Tm[which.max(PpG)],
              Pos = Pos[which.max(PpG)],
              Age = Age[which.max(PpG)],
              Games = G[which.max(PpG)],
              Shooting = TS.[which.max(PpG)],
              Top_PPG = max(round(PpG, 2))) %>%
    arrange(desc(Year))

TopScorer %>%
    mutate(Pos = cell_spec(Pos, color = "white", align = "c", 
                    background = factor(Pos, c("C", "PF", "SF", "SG", "PG"), 
                                        PosColorCode))) %>%
    kable(escape = FALSE, caption = "Annual Points per Game Leaders") %>%
    kable_styling("striped", full_width = T) %>%
    column_spec(1, bold = T, color = "yellow", background = "#FF0000") %>%
    column_spec(2, bold = T) %>%
    column_spec(8, bold = T, color = "white", background = "#777777") %>%
    scroll_box(width = "100%", height = "300px")
```

```{r TopScorers, warning = FALSE}
PPGmean <- NBA %>%
    group_by(Year) %>%
    summarise(meanPPG = mean(sum(PTS)/sum(G), na.rm = T))

TS <- TopScorer %>%
    ggplot() +
    geom_bar(aes(Year, Top_PPG, fill = Pos, text = paste("Player:", Player)), stat = "identity") +
    geom_line(aes(Year, meanPPG, linetype = "Average line"), data = PPGmean, color = "black") +
    ggtitle("Top Scorer by Year") +
    scale_x_continuous(breaks = seq(1950, 2020, 10)) +
    scale_fill_manual("Pos", values = PosColorCode) +
    ylab("Top Points per Game") +
    theme(legend.position='none')
```

```{r pts36, warning=FALSE}
PTS36 <- NBA %>%
    group_by(Player) %>%
    summarise(Pos = getmode(Pos),
              ActiveYears = paste(getmode(YearStart), "-", getmode(YearEnd)),
              Games = sum(G),
              MP = sum(MP),
              Points = sum(PTS),
              MPG = round(MP/Games, 2),
              PPG = round(Points/Games, 2),
              PPM36 = round(PPG/MPG * 36, 2)) %>%
    filter(Games > 100) %>%
    arrange(desc(PPM36)) %>%
    mutate(Rank = dense_rank(desc(PPM36))) %>%
    select(Rank, everything(), -c(MP, Points)) %>%
    head(n=20)

PTS36 %>%
    mutate(Pos = cell_spec(Pos,
                            color = "white",
                            align = "c",
                            background = factor(Pos, c("C", "PF", "SF", "SG", "PG"),
                                                PosColorCode))) %>%
    kable(escape = FALSE, caption = "Points per 36 Minutes") %>%
    kable_styling("striped", full_width = T) %>%
    column_spec(2, bold = T) %>%
    column_spec(1, bold = T, color = "yellow", background = "#FF0000") %>%
    column_spec(8, bold = T, color = "white", background = "#777777") %>%
    scroll_box(width = "100%", height = "300px")
```

```{r PTS36, fig.width=9, fig.height=5}
PTS36 %>%
    mutate(Player = reorder(Player, desc(PPM36), FUN=median)) %>%
    ggplot(aes(group = 1)) +
    geom_segment(aes(x=Player, xend=Player, y=PPM36, yend=PPG), color="black") +
    geom_point(aes(Player, PPM36, color="#FF5800"), size=5) +
    geom_point(aes(Player, PPG, color="#009dff"), size=3, shape=18) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Points per 36 Minutes vs. Points per Game") +
    xlab("") +
    ylab("PTS36 vs. PPG") +
    scale_color_manual(name="", values=c("#009dff", "#FF5800"),
                       labels=c("Points/Game", "Points/36 minutes"),
                       guide = guide_legend(reverse=TRUE)) +
    theme(legend.position="bottom")
``` 

```{r mostpts, warning=FALSE}
PTSMost <- NBA %>%
    group_by(Player) %>%
    filter(n_distinct(Born) == 1) %>%
    summarise(Pos = getmode(Position),
              ActiveYears = paste(getmode(YearStart), "-", getmode(YearEnd)),
              YearsActive = n_distinct(Year),
              Games = sum(G),
              MP = sum(MP),
              MPG = round(MP/Games, 2),
              Points = as.numeric(sum(PTS)),
              PPG = round(Points/Games, 2)) %>%
    filter(Games > 100) %>%
    arrange(desc(Points)) %>%
    head(n=20) %>%
    mutate(Rank = rank(desc(Points))) %>%
    select(Rank, everything(), -c(MP))


PTSMost %>%
    kable(escape = FALSE, caption = "Most Points Career") %>%
    kable_styling("striped", full_width = T) %>%
    column_spec(2, bold = T) %>%
    column_spec(1, bold = T, color = "yellow", background = "#FF0000") %>%
    column_spec(8, bold = T, color = "white", background = "#777777") %>%
    scroll_box(width = "100%", height = "300px")
```

```{r fig.width = 9, fig.height=5}
PTSMost %>%
    head(10) %>%
    arrange(Points) %>%
    mutate(Player=factor(Player, Player)) %>%
    ggplot(aes(Player, Points)) +
    geom_segment(aes(x=Player, xend=Player, y=0, yend=Points),
                 color="gray11", linetype = "dotted", size=1, alpha=0.6) +
    geom_point(color="orangered1", size=4) +
    geom_text(aes(label=Points), hjust=0.5, vjust=-1.5, size=3) +
    ggtitle("Most Points Career") +
    coord_flip() +
    xlab("") +
    ylab("Points")
```

```{r bestpts}
# Step 1: Calculating tokens for All-Time Points per Game leaderboard:
PTSValuation1 <- AllTimePPG %>%
    group_by(Player) %>%
    summarise(n = (ifelse(Rank == 1, 10, ifelse(Rank == 2, 7,
                        ifelse(Rank == 3, 4, ifelse(Rank%in%c(4:10), 2, 1)))))) %>%
    mutate(Player = as.character(Player)) %>%
    arrange(desc(n))

# Step 2: Calculating tokens for All-Time Points per Game leaderboard:
PTSValuation2 <- TopScorer %>% count(Player) %>% arrange(desc(n))

# Step 3: Calculating tokens for Points per 36 Minutes leaderboard:
PTSValuation3 <- PTS36 %>%
    group_by(Player) %>%
    filter(PPG > 18) %>%
    summarise(n = (ifelse(Rank == 1, 10, ifelse(Rank == 2, 7,
                        ifelse(Rank == 3, 4, ifelse(Rank%in%c(4:10), 2, 1)))))) %>%
    mutate(Player = as.character(Player)) %>%
    arrange(desc(n))

# Step 4: Calculating tokens for Most Points in career leaderboard:
PTSValuation4 <- PTSMost %>%
    group_by(Player) %>%
    summarise(n = (ifelse(Rank == 1, 10, ifelse(Rank == 2, 7, 
                    ifelse(Rank == 3, 4, ifelse(Rank%in%c(4:10), 2, 1)))))) %>%
    mutate(Player = as.character(Player)) %>%
    arrange(desc(n))

# Step 5: Merge the dataframes and calculating total tokens:
AllScorers <- data.frame(Player = c(PTSValuation1$Player,
                                    PTSValuation2$Player,
                                    PTSValuation3$Player,
                                    PTSValuation4$Player),
                         Tokens = c(PTSValuation1$n,
                                    PTSValuation2$n,
                                    PTSValuation3$n,
                                    PTSValuation4$n)) %>%
    group_by(Player) %>%
    summarise(Total = sum(Tokens)) %>%
    arrange(desc(Total))

# Step 6: Display the final table:
AllScorers %>%
    group_by(Player) %>%
    mutate(Pos = getmode(NBA$Position[NBA$Player %in% Player]),
           PPG = round(sum(NBA$PTS[NBA$Player %in% Player])/sum(NBA$G[NBA$Player %in% Player]), 2),
           Tokens = paste(strrep("|", Total))) %>%
    select(-Total,everything()) %>%
    filter(PPG > 16) %>%
    kable(escape = FALSE, caption = "BIGGEST Top Scorers") %>%
    kable_styling(bootstrap_options = "striped", full_width = F, font_size = 11) %>%
    column_spec(1, bold = T) %>%
    column_spec(4, bold = T, color = "gold") %>%
    column_spec(5, bold = T, color = "white", background = "#777777", width = "8px") %>%
    scroll_box(width = "50%", height = "500px") %>%
    kable_styling(position = "float_left")
```

```{r WCnames, fig.width=8, fig.height=4}
AllScorers %>%
    wordcloud2(size=0.4, color='random-light', backgroundColor="black")
```

```{r ptsratio, warning=FALSE}
SuperScorers <- NBA %>%
    filter(Player %in% head(AllScorers$Player, 8)) %>%
    group_by(Player) %>%
    summarise(Pos = getmode(Position),
              ActiveYears = paste(getmode(YearStart), "-", getmode(YearEnd)),
              YearsActive = n_distinct(Year),
              Games = sum(G),
              FGx2 = sum(X2P) * 2,
              FGx3 = sum(X3P, na.rm = T) * 3,
              FT = sum(FT),
              PTS = sum(PTS),
              PPG = round(PTS/Games, 2)) %>%
    arrange(desc(PPG))

SuperScorers %>%
    kable(escape = FALSE, caption = "SuperScorers 2Pts-3Pts-FT Ratio") %>%
    kable_styling("striped", full_width = T) %>%
    column_spec(1, bold = T)
```

```{r PTSratio, fig.width = 9}
SuperScorers %>%
    gather(Parameter, Points, -c(Player:Games, PTS:PPG)) %>%
    select(-c(Pos, Games, PTS)) %>%
    mutate(Player = factor(Player, levels = c("Kareem Abdul-Jabbar", "Kobe Bryant", "Karl Malone", "George Gervin", "LeBron James", "Kevin Durant", "Wilt Chamberlain", "Michael Jordan"))) %>%
    ggplot(aes(Player, Points, fill=forcats::fct_rev(Parameter))) +
    geom_bar( stat="identity", position="fill") +
    ggtitle("Points Breakdown Among SuperScorers") +
    coord_flip() +
    xlab("") +
    ylab("Shooting") +
    guides(fill = guide_legend(reverse = TRUE)) +
    theme(legend.position="bottom") +
    theme(legend.title=element_blank())
```

```{r RadarScore, warning=FALSE}
RadarScore <- NBA_Scaled %>%
    group_by(Player) %>%
    summarise(X2Pm = mean(X2P),
              X2Pa = mean(X2PA),
              X2P. = mean(X2P., na.rm=T),
              X3Pm = mean(X3P),
              X3Pa = mean(X3PA),
              X3P. = mean(X3P., na.rm=T),
              FTm = mean(FT),
              FTa = mean(FTA),
              FT. = mean(FT., na.rm=T),
              TS. = mean(TS., na.rm=T),
              eFG. = mean(eFG., na.rm=T)) %>%
    filter(Player %in% SuperScorers$Player) %>%
    select(-Player)

radarPPG <- plot_ly(type = 'scatterpolar',
        fill = 'toself',
        mode = 'lines') %>%
    add_trace(r = as.numeric(as.vector(RadarScore[7,])),
              theta = as.character(as.vector(colnames(RadarScore))),
              name = 'Michael Jordan') %>%
    add_trace(r = as.numeric(as.vector(RadarScore[4,])),
              theta = as.character(as.vector(colnames(RadarScore))),
              name = 'Kevin Durant') %>%
    add_trace(r = as.numeric(as.vector(RadarScore[6,])),
              theta = as.character(as.vector(colnames(RadarScore))),
              name = 'LeBron James') %>%
    add_trace(r = as.numeric(as.vector(RadarScore[3,])),
              theta = as.character(as.vector(colnames(RadarScore))),
              name = 'Karl Malone') %>%
    add_trace(r = as.numeric(as.vector(RadarScore[5,])),
              theta = as.character(as.vector(colnames(RadarScore))),
              name = 'Kobe Bryant') %>%
    layout(polar = list(radialaxis = list(visible = T,
                                          range = c(-1.5, 1.5))))
```